# Generated by Django 5.2 on 2025-05-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
    ]
