# Generated by Django 5.2 on 2025-05-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0002_remove_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
