# Generated by Django 5.2 on 2025-05-06 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0003_remove_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('salary', models.IntegerField()),
                ('jobtype', models.CharField(max_length=20)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
