# Generated by Django 5.2 on 2025-05-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0005_apply_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='pic',
        ),
    ]
