# Generated by Django 5.2 on 2025-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0006_remove_apply_job_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='job_id',
            field=models.CharField(default='job', max_length=20),
        ),
    ]
