# Generated by Django 5.2 on 2025-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0007_postjob_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='job_id',
            field=models.CharField(max_length=20),
        ),
    ]
