# Generated by Django 5.2 on 2025-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0008_alter_postjob_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='job_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
