# Generated by Django 5.2.7 on 2025-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='resume',
        ),
        migrations.AddField(
            model_name='apply_job',
            name='status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Under Review', max_length=20),
        ),
    ]
