# Generated by Django 5.2.7 on 2025-11-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0012_remove_apply_job_resume_apply_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
