# Generated by Django 5.2.7 on 2025-11-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehubapp', '0013_alter_apply_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
